name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=cover.out

    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@1f8f3abcccf7960749744fd13547965f0e7d1bdd
      uses: codecov/codecov-action@v1.2.2
      with:
        # Comma-separated list of files to upload
        files: 'cover.out'
